server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # Proxy MediaMTX API con CORS
    location /api/mediamtx/ {
        proxy_pass http://host.docker.internal:9997/;
        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Methods "GET, OPTIONS";
    }
}
